### ISSUE TITLE
[구현] Apollo Local Caching Logic 리서치 및 구현

### ISSUE THREAD

**Issue by greatSumini** [greatSumini/pickk-app#20]
**작업할 경로**
?? (업데이트 예정)

**구현물의 기능**
전역 상태 관리를 위한 Apollo local cache storage 사용법을 익히고, 구현한다.
유저정보들을 저장한다.

**주의사항/사이드이펙트 (선택)**
없음.

**Comment by orange-mush** [comment]
참고한 글들
1. [Apollo + Typescript](https://www.apollographql.com/docs/react/development-testing/static-typing/)
2. [Local state management](https://www.apollographql.com/docs/react/data/local-state/)
